GET http://localHost:3000/posts
Authorization: Bearer 

###

# This takes in the Refresh Token from when you login and returns a new Access Token
POST http://localhost:6000/token
Content-Type: application/json

{
    "token": ""
}

###

# This takes in the Refresh Token from when you login and removes it from DB so that user can no longer create new Access JWTs
DELETE http://localhost:6000/logout
Content-Type: application/json

{    
    "token": ""
}

###

POST http://localHost:6000/register
Content-Type: application/json

{
    "username": "Yazeed",
    "password": "password",
    "confirmPassword": "password",
    "email": "yazeed@email.com"
}

###

POST http://localHost:6000/login
Content-Type: application/json

{
    "username": "Yazeed",
    "password": "password"
}